# Generated by Django 5.0.4 on 2025-04-02 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.AddField(
            model_name='student',
            name='title',
            field=models.CharField(default=2, max_length=100, verbose_name='Логин'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='class_name',
            field=models.CharField(max_length=100, verbose_name='Класс'),
        ),
        migrations.AlterField(
            model_name='student',
            name='subject',
            field=models.CharField(max_length=100, verbose_name='Предмет'),
        ),
    ]
