# Generated by Django 5.0.4 on 2025-04-02 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_student_user_student_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='title',
            new_name='user',
        ),
    ]
