# Generated by Django 5.0.4 on 2025-04-02 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_students_delete_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Students',
        ),
    ]
